// src/data.js
export const data = [
    {
        id: 1,
        title: "Depression",
        description: [
            "Depression (major depressive disorder) is a common and serious medical illness that affects the way we",
            " feel, think, behave, and perceive the world. Symptoms of depression may vary from person to person ",
            "and in severity from mild to severe. These symptoms can include:",
            "• Feeling sad, irritable or empty.",
            "• Losing interest or pleasure in activities you once enjoyed",
            "• A significant change in appetite (eating much less or more than usual) and/or weight (notable loss or",
                " gain unrelated to dieting)",
            "• Insomnia or sleeping too much.",
            "• Decreased energy or increased tiredness or fatigue.",
            "• Reduce concentration, memory problems, and difficulty in making decisions",
            "• Increase in purposeless physical activity (e.g., inability to sit still, pacing, handwringing) or slowed ",
               "movements and speech that are enough to be observed by others.",
            "• Feeling worthless or excessively guilty",
            "• Feeling of hopelessness",
            "• Thoughts of death/death wishes, suicidal ideation, or suicide attempts.",
            "• Treatment modalities",
            "• Therapy",
            "• Medicines",
            "• Lifestyle modifications",
            "• Electro convulsive therapy",
        ],
    },
    {
        id: 2,
        title: "Child psychiatry",
        description: [
            "Child psychiatry Welcome to Healthy Minds & Kids Dental Care, where young minds find solace and support.",
             "As a child psychiatry clinic,we understand the delicate nature of nurturing mental well-being in our youngest",
            "patients.Our team is dedicated to providing compassionate care and evidence-based treatments tailored",
            "specifically for children and adolescents. Whether your child is navigating challenges such as anxiety,",
            "ADHD, or mood disorders, we're here to offer expert guidance and support every step of the way. At",
            "Healthy Minds & Kids Dental Care, we believe in empowering young minds to flourish and thrive. Welcome",
            "to a place where understanding meets healing, and where every child's journey to mental wellness is ",
            "honoured and respected.",
        ],
    },
    {
        id: 3,
        title: "Anxiety disorder",
        description: [
            "Anxiety is a normal reaction to stress. Mild levels can be beneficial in some situations (e.g. during exams).",
            "It can alert us to dangers and help us prepare and pay attention.",
            "Anxiety disorders are the commonest mental disorders and affect nearly 30 percent of adults at some",
            "point in their lives. They differ from normal feelings of nervousness/anxiousness and are characterized by",
            "excessive fear or anxiety. Anxiety disorders can cause people avoid situations that trigger or worsen their",
            " symptoms. Job performance, schoolwork and personal relationships can be affected. ",
            "Common symptoms are restlessness, uneasiness, palpitations, constant worries about something,",
            "sweating, tremors of hands/body, dryness of mouth,shortness of breath, cooling of peripheries, dizziness,etc.",
            "There are several types of anxiety disorders: generalized anxiety disorder, panic disorder with or without",
            "agoraphobia,specific phobias, agoraphobia, social anxiety disorder, separation anxiety disorder, and ",
            " selective mutism.",
            "Treatment",
            "Therapy",
            "Medicines (acute phase and long term)",
            " Lifestyle modifications",
        ],
    },
    {
        id: 4,
        title: "Schizophrenia",
        description: [
            "Schizophrenia",
            "Depression (major depressive disorder) is a common and serious medical illness that affects the way we",
            " feel, think, behave, and perceive the world. Symptoms of depression may vary from person to person ",
            "and in severity from mild to severe. These symptoms can include:",
            "• Feeling sad, irritable or empty.",
            "• Losing interest or pleasure in activities you once enjoyed",
            "• A significant change in appetite (eating much less or more than usual) and/or weight (notable loss or",
                " gain unrelated to dieting)",
            "• Insomnia or sleeping too much.",
            "• Decreased energy or increased tiredness or fatigue.",
            "• Reduce concentration, memory problems, and difficulty in making decisions",
            "• Increase in purposeless physical activity (e.g., inability to sit still, pacing, handwringing) or slowed ",
               "movements and speech that are enough to be observed by others.",
            "• Feeling worthless or excessively guilty",
            "• Feeling of hopelessness",
            "• Thoughts of death/death wishes, suicidal ideation, or suicide attempts.",
            "• Treatment modalities",
            "• Therapy",
            "• Medicines",
            "• Lifestyle modifications",
            "• Electro convulsive therapy",
        ],
    },
    {
        id: 5,
        title: "Healthy ways of Media use for Adults",
        description: [
            "Healthy ways of Media use for Adults",
            "Depression (major depressive disorder) is a common and serious medical illness that affects the way we",
            " feel, think, behave, and perceive the world. Symptoms of depression may vary from person to person ",
            "and in severity from mild to severe. These symptoms can include:",
            "• Feeling sad, irritable or empty.",
            "• Losing interest or pleasure in activities you once enjoyed",
            "• A significant change in appetite (eating much less or more than usual) and/or weight (notable loss or",
                " gain unrelated to dieting)",
            "• Insomnia or sleeping too much.",
            "• Decreased energy or increased tiredness or fatigue.",
            "• Reduce concentration, memory problems, and difficulty in making decisions",
            "• Increase in purposeless physical activity (e.g., inability to sit still, pacing, handwringing) or slowed ",
               "movements and speech that are enough to be observed by others.",
            "• Feeling worthless or excessively guilty",
            "• Feeling of hopelessness",
            "• Thoughts of death/death wishes, suicidal ideation, or suicide attempts.",
            "• Treatment modalities",
            "• Therapy",
            "• Medicines",
            "• Lifestyle modifications",
            "• Electro convulsive therapy",
        ],
    },
    {
        id: 6,
        title: "Recommended ways of media use in children",
        description: [
             "Recommended ways of media use in children",
            "Depression (major depressive disorder) is a common and serious medical illness that affects the way we",
            " feel, think, behave, and perceive the world. Symptoms of depression may vary from person to person ",
            "and in severity from mild to severe. These symptoms can include:",
            "• Feeling sad, irritable or empty.",
            "• Losing interest or pleasure in activities you once enjoyed",
            "• A significant change in appetite (eating much less or more than usual) and/or weight (notable loss or",
                " gain unrelated to dieting)",
            "• Insomnia or sleeping too much.",
            "• Decreased energy or increased tiredness or fatigue.",
            "• Reduce concentration, memory problems, and difficulty in making decisions",
            "• Increase in purposeless physical activity (e.g., inability to sit still, pacing, handwringing) or slowed ",
               "movements and speech that are enough to be observed by others.",
            "• Feeling worthless or excessively guilty",
            "• Feeling of hopelessness",
            "• Thoughts of death/death wishes, suicidal ideation, or suicide attempts.",
            "• Treatment modalities",
            "• Therapy",
            "• Medicines",
            "• Lifestyle modifications",
            "• Electro convulsive therapy",
        ],
    },
];
